/*
 @license
 OpenYOLO for Web
 Copyright 2017 The OpenYOLO for Web Authors. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 -----------------------------------------------------------------------------

 This file also contains code imported from tslib
 https://github.com/Microsoft/tslib

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
*****************************************************************************/
var w="function"==typeof Object.defineProperties?Object.defineProperty:function(f,c,d){f!=Array.prototype&&f!=Object.prototype&&(f[c]=d.value)},D="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function H(f,c){if(c){for(var d=D,h=f.split("."),k=0;k<h.length-1;k++){var e=h[k];e in d||(d[e]={});d=d[e]}h=h[h.length-1];k=d[h];e=c(k);e!=k&&null!=e&&w(d,h,{configurable:!0,writable:!0,value:e})}}
H("Object.setPrototypeOf",function(f){return f?f:"object"!=typeof"".__proto__?null:function(c,d){c.__proto__=d;if(c.__proto__!==d)throw new TypeError(c+" is not extensible");return c}});H("Object.assign",function(f){return f?f:function(c,d){for(var f=1;f<arguments.length;f++){var k=arguments[f];if(k)for(var e in k)Object.prototype.hasOwnProperty.call(k,e)&&(c[e]=k[e])}return c}});function L(){L=function(){};D.Symbol||(D.Symbol=M)}var N=0;function M(f){return"jscomp_symbol_"+(f||"")+N++}
function O(){L();var f=D.Symbol.iterator;f||(f=D.Symbol.iterator=D.Symbol("iterator"));"function"!=typeof Array.prototype[f]&&w(Array.prototype,f,{configurable:!0,writable:!0,value:function(){return W(this)}});O=function(){}}function W(f){var c=0;return X(function(){return c<f.length?{done:!1,value:f[c++]}:{done:!0}})}function X(f){O();f={next:f};f[D.Symbol.iterator]=function(){return this};return f}function Y(f){O();var c=f[Symbol.iterator];return c?c.call(f):W(f)}
H("Promise",function(f){function c(e){this.h=0;this.J=void 0;this.c=[];var c=this.A();try{e(c.resolve,c.reject)}catch(l){c.reject(l)}}function d(){this.c=null}if(f)return f;d.prototype.h=function(e){this.c||(this.c=[],this.A());this.c.push(e)};d.prototype.A=function(){var e=this;this.o(function(){e.J()})};var h=D.setTimeout;d.prototype.o=function(e){h(e,0)};d.prototype.J=function(){for(;this.c&&this.c.length;){var e=this.c;this.c=[];for(var c=0;c<e.length;++c){var f=e[c];delete e[c];try{f()}catch(u){this.C(u)}}}this.c=
null};d.prototype.C=function(e){this.o(function(){throw e;})};c.prototype.A=function(){function e(e){return function(d){f||(f=!0,e.call(c,d))}}var c=this,f=!1;return{resolve:e(this.Sa),reject:e(this.C)}};c.prototype.Sa=function(e){if(e===this)this.C(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof c)this.bb(e);else{a:switch(typeof e){case "object":var f=null!=e;break a;case "function":f=!0;break a;default:f=!1}f?this.Qa(e):this.ia(e)}};c.prototype.Qa=function(e){var c=void 0;
try{c=e.then}catch(l){this.C(l);return}"function"==typeof c?this.kb(c,e):this.ia(e)};c.prototype.C=function(e){this.na(2,e)};c.prototype.ia=function(e){this.na(1,e)};c.prototype.na=function(e,c){if(0!=this.h)throw Error("Cannot settle("+e+", "+c|"): Promise already settled in state"+this.h);this.h=e;this.J=c;this.Oa()};c.prototype.Oa=function(){if(this.c){for(var e=this.c,c=0;c<e.length;++c)e[c].call(),e[c]=null;this.c=null}};var k=new d;c.prototype.bb=function(c){var e=this.A();c.o(e.resolve,e.reject)};
c.prototype.kb=function(c,f){var e=this.A();try{c.call(f,e.resolve,e.reject)}catch(u){e.reject(u)}};c.prototype.then=function(e,f){function d(c,e){return"function"==typeof c?function(e){try{h(c(e))}catch(x){k(x)}}:e}var h,k,y=new c(function(c,e){h=c;k=e});this.o(d(e,h),d(f,k));return y};c.prototype["catch"]=function(c){return this.then(void 0,c)};c.prototype.o=function(c,f){function e(){switch(d.h){case 1:c(d.J);break;case 2:f(d.J);break;default:throw Error("Unexpected state: "+d.h);}}var d=this;
this.c?this.c.push(function(){k.h(e)}):k.h(e)};c.resolve=function(e){return e instanceof c?e:new c(function(c){c(e)})};c.reject=function(e){return new c(function(c,f){f(e)})};c.h=function(e){return new c(function(f,d){for(var h=Y(e),l=h.next();!l.done;l=h.next())c.resolve(l.value).o(f,d)})};c.c=function(e){var f=Y(e),d=f.next();return d.done?c.resolve([]):new c(function(e,h){function l(c){return function(f){k[c]=f;u--;u||e(k)}}var k=[],u=0;do k.push(void 0),u++,c.resolve(d.value).o(l(k.length-1),
h),d=f.next();while(!d.done)})};c.$jscomp$new$AsyncExecutor=function(){return new d};return c});
H("String.prototype.startsWith",function(f){return f?f:function(c,f){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this+"";c+="";for(var k=d.length,e=c.length,y=Math.max(0,Math.min(f|0,d.length)),l=0;l<e&&y<k;)if(d[y++]!=c[l++])return!1;return l>=e}});
(function(f){function c(a,b){function g(){this.constructor=a}Z(a,b);a.prototype=null===b?Object.create(b):(g.prototype=b.prototype,new g)}function d(a,b){var g=void 0;return new (g||(g=Promise))(function(p,c){function v(a){try{f(b.next(a))}catch(J){c(J)}}function e(a){try{f(b["throw"](a))}catch(J){c(J)}}function f(a){a.done?p(a.value):(new g(function(b){b(a.value)})).then(v,e)}f((b=b.apply(a,[])).next())})}function h(a,b){function g(a){return function(b){return p([a,b])}}function p(g){if(e)throw new TypeError("Generator is already executing.");
for(;c;)try{if(e=1,f&&(d=f[g[0]&2?"return":g[0]?"throw":"next"])&&!(d=d.call(f,g[1])).done)return d;if(f=0,d)g=[0,d.value];switch(g[0]){case 0:case 1:d=g;break;case 4:return c.label++,{value:g[1],done:!1};case 5:c.label++;f=g[1];g=[0];continue;case 7:g=c.$.pop();c.S.pop();continue;default:if(!(d=c.S,d=0<d.length&&d[d.length-1])&&(6===g[0]||2===g[0])){c=0;continue}if(3===g[0]&&(!d||g[1]>d[0]&&g[1]<d[3]))c.label=g[1];else if(6===g[0]&&c.label<d[1])c.label=d[1],d=g;else if(d&&c.label<d[2])c.label=d[2],
c.$.push(g);else{d[2]&&c.$.pop();c.S.pop();continue}}g=b.call(a,c)}catch(aa){g=[6,aa],f=0}finally{e=d=0}if(g[0]&5)throw g[1];return{value:g[0]?g[1]:void 0,done:!0}}var c={label:0,g:function(){if(d[0]&1)throw d[1];return d[1]},S:[],$:[]},e,f,d,h;return h={next:g(0),"throw":g(1),"return":g(2)},"function"===typeof Symbol&&(h[Symbol.iterator]=function(){return this}),h}function k(a){var b=Object.keys(a).reduce(function(b,c){b[c]=a[c].m;return b},Object.create(null));return Object.freeze(b)}function e(a){a=
ba.exec(a);if(!a)return null;var b={scheme:a[1],L:a[2]};a[3]&&(b.query=a[3]);a[4]&&(b.Ha=a[4]);return b}function y(a){return"undefined"===typeof a}function l(a){return"string"===typeof a&&0<a.length}function u(a){return"boolean"===typeof a}function P(a){if(!l(a))return!1;a=e(a);var b;(b=!a||a.query||a.Ha||!a.L.startsWith("//"))||(b=a.L.indexOf("/",a.L.startsWith("//")?2:0),b=0>b?null:a.L.substring(b));return b?!1:!0}function I(a){var b;!(b=!(a&&"object"===typeof a)||!l(a.id)||!P(a.authMethod)||"authDomain"in
a&&!P(a.authDomain)||"password"in a&&!l(a.password)||"displayName"in a&&!l(a.displayName))&&(b="profilePicture"in a)&&(b=a.profilePicture,l(b)?(b=e(b),b=!b||"http"!==b.scheme&&"https"!==b.scheme||!b.L.startsWith("//")?!1:!!b):b=!1,b=!b);return b||"exchangeToken"in a&&!l(a.exchangeToken)||"idToken"in a&&!l(a.idToken)||"generatedPassword"in a&&!l(a.generatedPassword)||"proxiedAuthRequired"in a&&!u(a.proxiedAuthRequired)?!1:!0}function Q(){return!0}function R(){return!0}function q(a){return function(b){return!!b&&
"object"===typeof b&&"id"in b&&"string"===typeof b.id&&a(b.args)}}function x(a,b,g){return{type:a,data:{id:b,args:g,ack:!1}}}function A(a,b){function g(g){var c=g.data;if(!(c&&"object"===typeof c&&"type"in c&&"data"in c))return console.debug("non openyolo message received"),!1;if(g.data.type!==a)return!1;if(!(0,ca[a])(g.data.data))return console.debug("message of type "+a+" received with invalid data"),!1;b(g.data.data,g.data.type,g);return!0}g.toString=function(){return a+" message listener"};return g}
function S(){var a=new Uint32Array(2);window.crypto.getRandomValues(a);return a[0].toString(16)+a[1].toString(16)}function T(a){return d(this,function(){var b,g;return h(this,function(c){switch(c.label){case 0:if(!K)return[2,Promise.resolve(a)];if("undefined"!==typeof TextEncoder)c=(new TextEncoder("utf-8")).encode(a);else{c=[];for(var e=0,d=0;d<a.length;d++){var f=a.charCodeAt(d);128>f?c[e++]=f:2048>f?(c[e++]=f>>6|192,c[e++]=f&63|128):55296===(f&64512)&&d+1<a.length&&56320===(a.charCodeAt(d+1)&64512)?
(f=65536+((f&1023)<<10)+(a.charCodeAt(++d)&1023),c[e++]=f>>18|240,c[e++]=f>>12&63|128,c[e++]=f>>6&63|128,c[e++]=f&63|128):(c[e++]=f>>12|224,c[e++]=f>>6&63|128,c[e++]=f&63|128)}c=new Uint8Array(c)}b=c;return[4,K.digest("SHA-256",b)];case 1:g=c.g();c=[];e=new DataView(g);for(d=0;d<e.byteLength;d+=4)f=("00000000"+e.getUint32(d).toString(16)).slice(-8),c.push(f);return[2,c.join("")]}})})}function da(){var a=window;E&&a.removeEventListener("message",E);E=A(z.nb,function(a,g,c){console.debug("responding to ping from "+
c.origin);c.source.postMessage({type:z.mb,data:a},c.origin||"*")});a.addEventListener("message",E)}var Z=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},m=Object.assign||function(a){for(var b,c=1,e=arguments.length;c<e;c++){b=arguments[c];for(var d in b)Object.prototype.hasOwnProperty.call(b,d)&&(a[d]=b[d])}return a},B=Object.freeze({Aa:"bottomSheet",Ra:"navPopout",fullScreen:"fullScreen"}),ea=k({tb:{m:"openyolo://id-and-password"},
ya:{m:"https://accounts.google.com"},sb:{m:"https://www.facebook.com"},ub:{m:"https://www.linkedin.com"},za:{m:"https://login.live.com"},wb:{m:"https://www.paypal.com"},zb:{m:"https://twitter.com"},Ab:{m:"https://login.yahoo.com"}}),fa=k({ya:{m:"https://accounts.google.com"},za:{m:"https://login.live.com"}}),n=Object.freeze({fa:"ackTimeout",T:"canceled",U:"clientDisposed",Ia:"handshakeFailed",la:"invalidCredential",ma:"invalidData",La:"iframeError",Cb:"invalidOrigin",ea:"untrustedOrigin",va:"requestFailed",
N:"requestTimeout",Ma:"illegalState",ja:"illegalConcurrentRequest",P:"establishSecureChannelTimeout",xa:"unknownRequest",ga:"apiDisabled",Ta:"parentVerifyTimeout",ra:"parentIsNotRoot",sa:"providerInitFailed",da:"unknown"}),r=function(){function a(){}a.fa=function(){return a.a({code:n.fa,message:"Message acknowledgement timed out."})};a.T=function(){return a.a({code:n.T,message:"User canceled"})};a.U=function(){return a.a({code:n.U,message:"Client is disposed and no longer usable"})};a.o=function(b){return a.a({code:n.Ia,
message:b})};a.la=function(){return a.a({code:n.la,message:"The provided credential is invalid"})};a.ma=function(){return a.a({code:n.ma,message:"Message contained invalid data"})};a.A=function(b){return a.a({code:n.La,message:"IFrame error: "+b})};a.ea=function(b){return a.a({code:n.ea,message:"Untrusted origin: "+b})};a.va=function(b){return a.a({code:n.va,message:b})};a.N=function(){return a.a({code:n.N,message:"Request timed out"})};a.ka=function(b){return a.a({code:n.Ma,message:b})};a.C=function(){return a.a({code:n.ja,
message:"Concurrent requests are not permitted"})};a.P=function(){return a.a({code:n.P,message:"SecureConnection establishment timed out"})};a.xa=function(b){return a.a({code:n.xa,message:"Unknown request type "+b})};a.ga=function(){return a.a({code:n.ga,message:"API is disabled"})};a.da=function(){return a.a({code:n.da,message:"Unknown error"})};a.c=function(){return a.a({code:n.Ta,message:"Frame ancestor origin verification timed out"})};a.ra=function(){return a.a({code:n.ra,message:"Parent frame is not a root window"})};
a.sa=function(){return a.a({code:n.sa,message:"Provider failed to initialize"})};a.a=function(a){var b=Error(a.message);b.data=a;return b};a.h=function(a,c){return"data"in a?a.data.code===c:!1};return a}(),ba=/^(?:([^:/?#]+):)((?:\/\/)?[^?#]*)(?:\\?([^#]*))?(?:#([^?]*))?$/,z=Object.freeze({ack:"ack",nb:"verifyPing",mb:"verifyAck",ua:"readyForConnect",Ba:"channelConnect",Ca:"channelReady",Bb:"channelError"}),F={ack:l,verifyPing:l,verifyAck:l,readyForConnect:l,channelConnect:l,channelReady:l,channelError:R},
t=Object.freeze({v:"retrieve",Ja:"hintAvailable",Ka:"hintAvailableResult",hint:"hint",save:"save",cb:"saveResult",Wa:"proxy",Za:"proxyResult",G:"wrapBrowser",ob:"wrapBrowserResult",Db:"showProvider",pa:"none",credential:"credential",error:"error"}),ca=m({},F,{retrieve:q(function(){return!0}),hintAvailable:q(Q),hintAvailableResult:q(u),hint:q(Q),save:q(I),saveResult:q(u),proxy:q(I),proxyResult:q(function(){return!0}),wrapBrowser:q(y),wrapBrowserResult:q(u),showProvider:q(function(){return!0}),none:q(y),
credential:q(I),error:q(R)}),K=null;window.crypto&&(K=window.crypto.subtle||window.crypto.webkitSubtle);var G=function(){function a(){var a=this;this.i=new Promise(function(b,c){a.ba=b;a.R=c})}a.prototype.resolve=function(a){if(!this.ba)throw Error("Promise Resolver already disposed.");this.ba(a);this.dispose()};a.prototype.reject=function(a){if(!this.R)throw Error("Promise Resolver already disposed.");this.R(a);this.dispose()};a.prototype.dispose=function(){this.R=this.ba=null};return a}(),U=function(a){function b(b,
c){var g=a.call(this)||this;g.ib=b;g.wa=setTimeout(g.jb.bind(g),c);return g}c(b,a);b.prototype.resolve=function(b){a.prototype.resolve.call(this,b);clearTimeout(this.wa)};b.prototype.reject=function(b){a.prototype.reject.call(this,b);clearTimeout(this.wa)};b.prototype.jb=function(){this.R&&this.reject(this.ib)};return b}(G),ga=function(){function a(a,c){var b=this;this.port=a;this.Va=c;this.u=[];this.X=[];this.oa=function(a){for(var c=!1,g=0;g<b.u.length;g++){var e=b.u[g];e&&(c=!!e.Ua(a)||c)}if(!c)for(b.b("no registered listeners to handle received message:"+
JSON.stringify(a.data)),g=0;g<b.X.length;g++)b.X[g](a)};this.port.addEventListener("message",this.oa);this.port.start()}a.Ea=function(b,c,e){var g=window;var d=0<d?d:3E3;var f=r.P();d=(new U(f,d)).i;b=a.c(g,b,c,e);return Promise.race([d,b])};a.c=function(b,c,e,f){return d(this,function(){var g,d,p,v,k;return h(this,function(h){switch(h.label){case 0:return a.b("client","waiting for ready message from credential provider"),[4,a.h(b,f)];case 1:h.g(),g=new MessageChannel,d=new G,p=A("channelReady",function(){d.resolve()}),
v=A("channelError",function(a){d.reject(r.a(a))}),b.addEventListener("message",p),b.addEventListener("message",v),a.b("client","sending connection challenge to provider"),c.postMessage({type:z.Ba,data:e},"*",[g.port2]),h.label=2;case 2:return h.S.push([2,4,5,6]),[4,d.i];case 3:return h.g(),a.b("client","credential provider accepted connection"),[2,new a(g.port1,!1)];case 4:throw k=h.g(),a.b("client","credential provider rejected connection: "+k.code),g.port1.close(),k;case 5:return b.removeEventListener("message",
p),b.removeEventListener("message",v),[7];case 6:return[2]}})})};a.h=function(a,c){var b=new G,g=A(z.ua,function(a){c===a&&b.resolve()});a.addEventListener("message",g);b.i.then(function(){a.removeEventListener("message",g)},function(){a.removeEventListener("message",g)});return b.i};a.o=function(b,c,e,f){return d(this,function(){var g,p,v;return h(this,function(){g=null;p=new U(r.P(),f&&0<f?f:3E3);v=A("channelConnect",function(f,v,k){return d(this,function(){var d;return h(this,function(h){switch(h.label){case 0:return a.b("provider",
"connection challenge received from "+k.origin),"string"!==typeof f?(a.b("provider","challenge nonce is not a string - ignoring"),[2]):[4,T(f)];case 1:d=h.g();if(d!==e)return a.b("provider","challenge nonce did not match - ignoring"),[2];if(-1===c.indexOf(k.origin))return a.b("provider","connection challenge from untrusted origin - rejecting"),p.reject(r.ea(k.origin)),[2];if(!k.ports)return a.b("provider","connection challenge did not carry a port - rejecting"),p.reject(r.ka("channel initialization message does not contain ports")),
[2];a.b("provider","accepted connection from "+k.origin);g=k.ports[0];b.parent.postMessage({type:z.Ca,data:e},k.origin);p.resolve(new a(g,!0));return[2]}})})});b.addEventListener("message",v);p.i.then(function(){b.removeEventListener("message",v)},function(){b.removeEventListener("message",v)});a.b("provider","sending ready to connect message to client");b.parent.postMessage({type:z.ua,data:e},"*");return[2,p.i]})})};a.b=function(a,c){console.debug("("+a+") "+c)};a.prototype.send=function(a){this.port.postMessage(a)};
a.prototype.Pa=function(a,c){var b=this;if(!a||!c)throw r.ka("invalid type or listener");this.u.push({Ua:A(a,function(a,g,d){a.ack&&b.port.postMessage({type:z.ack,data:a.id});c(a,g,d)}),Eb:c});return this.u.length-1};a.prototype.lb=function(a){this.u[a]&&(this.u[a]=null)};a.prototype.b=function(b){a.b(this.Va?"provider":"client",b)};a.prototype.dispose=function(){this.b("disposing channel");this.port.removeEventListener("message",this.oa);this.X=this.u=null;this.port.close()};return a}(),m=function(){function a(a,
c,d){void 0===d&&(d=S());var b=this;this.frame=a;this.channel=c;this.id=d;this.s=new G;this.Z=[];this.ca=[];this.I=!1;this.b("request instantiated");this.l("error",function(a){a=a?r.a(a):r.da();b.b("request failed: "+a);b.reject(a);b.dispose()});this.l("showProvider",function(c){b.w();a.display(c)})}a.prototype.b=function(a){console.debug("(rq-"+this.id+"): "+a)};a.prototype.resolve=function(a){this.s.resolve(a);this.frame.ha()};a.prototype.reject=function(a){this.s.reject(a);a.data.code!==n.ja&&
this.frame.ha()};a.prototype.l=function(a,c){function b(b,d,e){if(b.id!==g.id)return!1;c(b.args,a,e)}var g=this;b.toString=function(){return a+" message handler"};this.Z.push(this.channel.Pa(a,b))};a.prototype.Da=function(){var a=this;this.Z.forEach(function(b){a.channel.lb(b)});this.Z=[]};a.prototype.O=function(a,c){this.ca.push(window.setTimeout(function(){return a()},c))};a.prototype.w=function(){this.ca.forEach(function(a){window.clearTimeout(a)});this.ca=[]};a.prototype.dispose=function(){this.I||
(this.w(),this.Da(),this.s.dispose(),this.I=!0)};return a}(),ha=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}c(b,a);b.prototype.j=function(a){var b=this;this.l(t.credential,function(a){return b.K(a)});this.l(t.pa,function(){return b.K(null)});this.O(function(){b.reject(r.N());b.dispose()},5E3);this.channel.send(x(t.v,this.id,a));return this.s.i};b.prototype.K=function(a){this.w();this.resolve(a);this.dispose()};return b}(m),ia=function(a){function b(){return null!==a&&a.apply(this,
arguments)||this}c(b,a);b.prototype.j=function(a){var b=this;this.l(t.cb,function(a){a?b.resolve():b.reject(r.T());b.dispose()});this.channel.send(x(t.save,this.id,a));return this.s.i};return b}(m),ja=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}c(b,a);b.prototype.j=function(a,b){var c=this;this.l(t.Ka,function(a){c.w();c.resolve(a);c.dispose()});this.O(function(){c.resolve(!1);c.dispose()},b&&0<b?b:1E3);this.channel.send(x(t.Ja,this.id,a));return this.s.i};return b}(m),
ka=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}c(b,a);b.prototype.j=function(a){var b=this;this.l(t.credential,function(a){return b.K(a)});this.l(t.pa,function(){return b.K(null)});this.O(function(){b.reject(r.N());b.dispose()},5E3);this.b("Sending hint request");this.channel.send(x(t.hint,this.id,a));return this.s.i};b.prototype.K=function(a){this.b("Hint request complete");this.w();this.resolve(a);this.dispose()};return b}(m),C,la=function(){function a(a,c,d,e,f,h){this.V=
a;this.Na=c;this.M=e;C||(C=document.createElement("style"),C.type="text/css",C.appendChild(document.createTextNode("\n.openyolo-hidden {\n  display: none;\n}\n\n.openyolo-visible {\n  position: fixed;\n  border: none;\n  z-index: 9999;\n}\n\n.openyolo-visible.bottomSheet {\n  bottom: 0;\n  left: 0;\n  width: 100%;\n  height: 320px;\n}\n\n.openyolo-visible.navPopout {\n  top: 0;\n  right: 0;\n  width: 320px;\n  height: 320px;\n}\n\n.openyolo-visible.fullScreen {\n  top: 0;\n  left: 0;\n  width: 100%;\n  height: 100%;\n}\n")),
document.getElementsByTagName("head")[0].appendChild(C));this.f=this.V.createElement("iframe");this.f.src=""+f+("?client="+encodeURIComponent(d))+("&id="+this.Na)+("&renderMode="+e);h&&(a=encodeURIComponent(JSON.stringify(h)),this.f.src+="&preloadRequest="+a);this.f.className="openyolo-hidden";this.V.body.appendChild(this.f)}a.prototype.display=function(a){this.f.className="";this.f.classList.add("openyolo-visible");this.f.classList.add(this.M);(a.height||a.width)&&this.M!==B.fullScreen&&(a.height&&
(this.f.style.height=a.height+"px"),a.width&&(this.f.style.width=a.width+"px"))};a.prototype.ha=function(){this.f.className="openyolo-hidden";this.f.style.height="";this.f.style.width=""};a.prototype.dispose=function(){this.V.body.removeChild(this.f)};return a}(),ma=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}c(b,a);b.prototype.j=function(a){var b=this;this.l(t.Za,function(a){b.resolve(a);b.dispose()});this.O(function(){b.reject(r.N());b.dispose()},1E4);this.channel.send(x(t.Wa,
this.id,a));return this.s.i};return b}(m),na=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}c(b,a);b.prototype.j=function(a){var b=this;this.l(t.ob,function(a){b.w();b.resolve(a);b.dispose()});this.O(function(){b.resolve(!1);b.dispose()},a&&0<a?a:1E3);this.channel.send(x(t.G,this.id,void 0));return this.s.i};return b}(m),E,V=Object.freeze({hint:"hint",v:"retrieve"}),oa=/android|iphone|ipod|iemobile/i,pa=function(){function a(a,c,d){this.B=a;this.channel=c;this.G=d;this.I=
!1}a.create=function(b,c,e){return d(this,function(){var d,f,g,k,l,m,n,p;return h(this,function(h){switch(h.label){case 0:return d=S(),[4,T(d)];case 1:return f=h.g(),c&&c in B||(g=navigator.userAgent.match(oa),c=(k=window.parent!==window)?B.fullScreen:g?B.Aa:B.Ra),l=new la(document,f,window.location.origin,c,b,e),[4,ga.Ea(l.f.contentWindow,d,f)];case 2:return m=h.g(),n=new na(l,m),[4,n.j()];case 3:return p=h.g(),[2,new a(l,m,p)]}})})};a.prototype.Y=function(a,c){return d(this,function(){var b;return h(this,
function(){this.H();b=new ja(this.B,this.channel);return[2,b.j(a,c)]})})};a.prototype.hint=function(a){return d(this,function(){var b;return h(this,function(){this.H();b=new ka(this.B,this.channel);return[2,b.j(a)]})})};a.prototype.v=function(a){return d(this,function(){return h(this,function(){this.H();return this.G?[2,this.$a()]:[2,this.ab(a)]})})};a.prototype.$a=function(){return d(this,function(){return h(this,function(){return[2,Promise.reject("not implemented")]})})};a.prototype.ab=function(a){return(new ha(this.B,
this.channel)).j(a)};a.prototype.save=function(a){return d(this,function(){return h(this,function(){this.H();this.G?this.eb():this.fb(a);return[2]})})};a.prototype.eb=function(){d(this,function(){return h(this,function(){return[2,Promise.reject("not implemented")]})})};a.prototype.fb=function(a){d(this,function(){var b;return h(this,function(){b=new ia(this.B,this.channel);return[2,b.j(a)]})})};a.prototype.W=function(){return d(this,function(){return h(this,function(){this.H();this.G?this.Fa():this.Ga();
return[2,null]})})};a.prototype.dispose=function(){this.I||(this.channel.dispose(),this.B.dispose())};a.prototype.H=function(){if(this.I)throw r.U();};a.prototype.Fa=function(){d(this,function(){return h(this,function(){Promise.reject("not implemented");return[2]})})};a.prototype.Ga=function(){d(this,function(){return h(this,function(){Promise.reject("not implemented");return[2]})})};a.prototype.aa=function(a){return d(this,function(){return h(this,function(){if(this.G)this.Xa();else return[2,this.Ya(a)];
return[2]})})};a.prototype.Xa=function(){d(this,function(){return h(this,function(){return[2,Promise.reject("not implemented")]})})};a.prototype.Ya=function(a){return d(this,function(){var b;return h(this,function(){b=new ma(this.B,this.channel);return[2,b.j(a)]})})};return a}(),m=function(){function a(){this.ta="https://provider.openyolo.org";this.M=this.D=null;da()}a.prototype.gb=function(a){this.ta=a;this.reset()};a.prototype.hb=function(a){this.M=a;this.reset()};a.prototype.reset=function(){if(this.D){var a=
this.D;this.D=null;a.then(function(a){a.dispose()})}};a.prototype.F=function(a){this.D||(this.D=pa.create(this.ta,this.M,a));return this.D};a.prototype.Y=function(a){return d(this,function(){return h(this,function(b){switch(b.label){case 0:return[4,this.F()];case 1:return[2,b.g().Y(a)]}})})};a.prototype.hint=function(a){return d(this,function(){return h(this,function(b){switch(b.label){case 0:return[4,this.F({type:V.hint,options:a})];case 1:return[2,b.g().hint(a)]}})})};a.prototype.v=function(a){return d(this,
function(){return h(this,function(b){switch(b.label){case 0:return[4,this.F({type:V.v,options:a})];case 1:return[2,b.g().v(a)]}})})};a.prototype.save=function(a){return d(this,function(){return h(this,function(b){switch(b.label){case 0:return[4,this.F()];case 1:return[2,b.g().save(a)]}})})};a.prototype.W=function(){return d(this,function(){return h(this,function(a){switch(a.label){case 0:return[4,this.F()];case 1:return[2,a.g().W()]}})})};a.prototype.aa=function(a){return d(this,function(){return h(this,
function(b){switch(b.label){case 0:return[4,this.F()];case 1:return[2,b.g().aa(a)]}})})};return a}(),F=new m;window.openyolo=F;m.prototype.setProviderUrlBase=m.prototype.gb;m.prototype.setRenderMode=m.prototype.hb;m.prototype.hintsAvailable=m.prototype.Y;m.prototype.hint=m.prototype.hint;m.prototype.retrieve=m.prototype.v;m.prototype.save=m.prototype.save;m.prototype.disableAutoSignIn=m.prototype.W;m.prototype.proxyLogin=m.prototype.aa;f.qb=3E3;f.qa=F;f.vb=r;f.rb=n;f.xb=B;f.pb=ea;f.yb=fa})(this.qa=
this.qa||{});
'use strict';var l="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)},m="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,n=function(a,c){if(c){var d=m;a=a.split(".");for(var b=0;b<a.length-1;b++){var f=a[b];f in d||(d[f]={});d=d[f]}a=a[a.length-1];b=d[a];c=c(b);c!=b&&null!=c&&l(d,a,{configurable:!0,writable:!0,value:c})}};
n("Object.assign",function(a){return a?a:function(a,d){for(var b=1;b<arguments.length;b++){var c=arguments[b];if(c)for(var g in c)Object.prototype.hasOwnProperty.call(c,g)&&(a[g]=c[g])}return a}});
var p=function(){p=function(){};m.Symbol||(m.Symbol=r)},t=0,r=function(a){return"jscomp_symbol_"+(a||"")+t++},v=function(){p();var a=m.Symbol.iterator;a||(a=m.Symbol.iterator=m.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&l(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return u(this)}});v=function(){}},u=function(a){var c=0;return w(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})},w=function(a){v();a={next:a};a[m.Symbol.iterator]=function(){return this};
return a},x=function(a){v();var c=a[Symbol.iterator];return c?c.call(a):u(a)};
n("Promise",function(a){function c(){this.a=null}if(a)return a;c.prototype.m=function(a){null==this.a&&(this.a=[],this.w());this.a.push(a)};c.prototype.w=function(){var a=this;this.o(function(){a.B()})};var d=m.setTimeout;c.prototype.o=function(a){d(a,0)};c.prototype.B=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;++b){var e=a[b];delete a[b];try{e()}catch(h){this.A(h)}}}this.a=null};c.prototype.A=function(a){this.o(function(){throw a;})};var b=function(a){this.c=
0;this.j=void 0;this.b=[];var b=this.g();try{a(b.resolve,b.reject)}catch(e){b.reject(e)}};b.prototype.g=function(){function a(a){return function(g){e||(e=!0,a.call(b,g))}}var b=this,e=!1;return{resolve:a(this.F),reject:a(this.i)}};b.prototype.F=function(a){if(a===this)this.i(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.G(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.D(a):this.s(a)}};b.prototype.D=
function(a){var b=void 0;try{b=a.then}catch(e){this.i(e);return}"function"==typeof b?this.H(b,a):this.s(a)};b.prototype.i=function(a){this.u(2,a)};b.prototype.s=function(a){this.u(1,a)};b.prototype.u=function(a,b){if(0!=this.c)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.c);this.c=a;this.j=b;this.C()};b.prototype.C=function(){if(null!=this.b){for(var a=this.b,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.b=null}};var f=new c;b.prototype.G=function(a){var b=this.g();
a.f(b.resolve,b.reject)};b.prototype.H=function(a,b){var c=this.g();try{a.call(b,c.resolve,c.reject)}catch(h){c.reject(h)}};b.prototype.then=function(a,c){function e(a,b){return"function"==typeof a?function(b){try{h(a(b))}catch(F){d(F)}}:b}var h,d,f=new b(function(a,b){h=a;d=b});this.f(e(a,h),e(c,d));return f};b.prototype.f=function(a,b){function c(){switch(h.c){case 1:a(h.j);break;case 2:b(h.j);break;default:throw Error("Unexpected state: "+h.c);}}var h=this;null==this.b?f.m(c):this.b.push(function(){f.m(c)})};
b.resolve=function(a){return a instanceof b?a:new b(function(b){b(a)})};b.reject=function(a){return new b(function(b,c){c(a)})};b.race=function(a){return new b(function(c,e){for(var h=x(a),d=h.next();!d.done;d=h.next())b.resolve(d.value).f(c,e)})};b.all=function(a){var c=x(a),d=c.next();return d.done?b.resolve([]):new b(function(a,e){function h(b){return function(c){f[b]=c;g--;0==g&&a(f)}}var f=[],g=0;do f.push(void 0),g++,b.resolve(d.value).f(h(f.length-1),e),d=c.next();while(!d.done)})};b.$jscomp$new$AsyncExecutor=
function(){return new c};return b});var y;y="undefined"!==typeof window?window:"undefined"!==typeof self?self:global;
var __extends=function(a,c){function d(){this.constructor=a}for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b]);a.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)},__assign=Object.assign||function(a){for(var c,d=1,b=arguments.length;d<b;d++){c=arguments[d];for(var f in c)Object.prototype.hasOwnProperty.call(c,f)&&(a[f]=c[f])}return a},__rest=function(a,c){var d={},b;for(b in a)Object.prototype.hasOwnProperty.call(a,b)&&0>c.indexOf(b)&&(d[b]=a[b]);if(null!=a&&"function"===typeof Object.getOwnPropertySymbols){var f=
0;for(b=Object.getOwnPropertySymbols(a);f<b.length;f++)0>c.indexOf(b[f])&&(d[b[f]]=a[b[f]])}return d},__decorate=function(a,c,d,b){var f=arguments.length,g=3>f?c:null===b?b=Object.getOwnPropertyDescriptor(c,d):b;var k=y.Reflect;if("object"===typeof k&&k&&"function"===typeof k.decorate)g=k.decorate(a,c,d,b);else for(var e=a.length-1;0<=e;e--)if(k=a[e])g=(3>f?k(g):3<f?k(c,d,g):k(c,d))||g;return 3<f&&g&&Object.defineProperty(c,d,g),g},__metadata=function(a,c){var d=y.Reflect;if("object"===typeof d&&
d&&"function"===typeof d.metadata)return d.metadata(a,c)},__param=function(a,c){return function(d,b){c(d,b,a)}},__awaiter=function(a,c,d,b){return new (d||(d=Promise))(function(f,g){function k(a){try{h(b.next(a))}catch(q){g(q)}}function e(a){try{h(b["throw"](a))}catch(q){g(q)}}function h(a){a.done?f(a.value):(new d(function(b){b(a.value)})).then(k,e)}h((b=b.apply(a,c)).next())})},__generator=function(a,c){function d(a){return function(c){return b([a,c])}}function b(b){if(g)throw new TypeError("Generator is already executing.");
for(;f;)try{if(g=1,k&&(e=k[b[0]&2?"return":b[0]?"throw":"next"])&&!(e=e.call(k,b[1])).done)return e;if(k=0,e)b=[0,e.value];switch(b[0]){case 0:case 1:e=b;break;case 4:return f.label++,{value:b[1],done:!1};case 5:f.label++;k=b[1];b=[0];continue;case 7:b=f.h.pop();f.l.pop();continue;default:if(!(e=f.l,e=0<e.length&&e[e.length-1])&&(6===b[0]||2===b[0])){f=0;continue}if(3===b[0]&&(!e||b[1]>e[0]&&b[1]<e[3]))f.label=b[1];else if(6===b[0]&&f.label<e[1])f.label=e[1],e=b;else if(e&&f.label<e[2])f.label=e[2],
f.h.push(b);else{e[2]&&f.h.pop();f.l.pop();continue}}b=c.call(a,f)}catch(E){b=[6,E],k=0}finally{g=e=0}if(b[0]&5)throw b[1];return{value:b[0]?b[1]:void 0,done:!0}}var f={label:0,I:function(){if(e[0]&1)throw e[1];return e[1]},l:[],h:[]},g,k,e;return{next:d(0),"throw":d(1),"return":d(2)}};
"undefined"!==typeof y.v&&y.v||(y.__extends=__extends,y.__assign=__assign,y.__rest=__rest,y.__extends=__extends,y.__decorate=__decorate,y.__metadata=__metadata,y.__param=__param,y.__awaiter=__awaiter,y.__generator=__generator);var z=/^openyolo:\/\/\//,A=/^smartlock:\/\/\//,B=function(){},C=function(a){return a.replace(z,"smartlock://")},D=function(a){return{id:a.id,authMethod:a.authMethod.replace(A,"openyolo://"),authDomain:a.authDomain,displayName:a.displayName,profilePicture:a.profilePicture,idToken:a.idToken}};B.prototype.hintsAvailable=function(a){a={supportedAuthMethods:a.supportedAuthMethods.map(C),supportedIdTokenProviders:a.supportedIdTokenProviders};return openyolo.hintsAvailable(a)};
B.prototype.hintsAvailable=B.prototype.hintsAvailable;B.prototype.hint=function(a){a={supportedAuthMethods:a.supportedAuthMethods.map(C),supportedIdTokenProviders:a.supportedIdTokenProviders};return openyolo.hint(a).then(D)};B.prototype.hint=B.prototype.hint;B.prototype.retrieve=function(a){a={supportedAuthMethods:a.supportedAuthMethods.map(C),supportedIdTokenProviders:a.supportedIdTokenProviders};return openyolo.retrieve(a).then(D)};B.prototype.retrieve=B.prototype.retrieve;var G=new B,H=window;
H.smartlock=G;window.smartlock=G;document.addEventListener("DOMContentLoaded",function(){if(H.onSmartLockLoad)H.onSmartLockLoad(G)});
